const SAVE_USER = "SAVE_USER";
const REMOVE_USER = "REMOVE_USER";
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
const FETCH_PENDING = "FETCH_PENDING";
const FETCH_SUCCESSFUL = "FETCH_SUCCESSFUL";
const FETCH_REJECTED = "FETCH_REJECTED";
const FETCH_SINGLE_BOOK_PENDING = "FETCH_SINGLE_BOOK_PENDING";
const FETCH_SINGLE_BOOK_SUCCESSFUL = "FETCH_SINGLE_BOOK_SUCCESSFUL";
const FETCH_SINGLE_BOOK_REJECTED = "FETCH_SINGLE_BOOK_REJECTED";
const SAVE_SINGLE_ITEM = "SAVE_SINGLE_ITEM";

export {
  SAVE_USER,
  REMOVE_USER,
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  FETCH_PENDING,
  FETCH_SUCCESSFUL,
  FETCH_REJECTED,
  FETCH_SINGLE_BOOK_PENDING,
  FETCH_SINGLE_BOOK_SUCCESSFUL,
  FETCH_SINGLE_BOOK_REJECTED,
  SAVE_SINGLE_ITEM,
};
