const SAVE_USER = "SAVE_USER";
const REMOVE_USER = "REMOVE_USER";
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";

// FETCH BOOKS FROM GOOGLE API
const FETCH_ALL_BOOKS_FROM_GOOGLE_PENDING =
  "FETCH_ALL_BOOKS_FROM_GOOGLE_PENDING";
const FETCH_ALL_BOOKS_FROM_GOOGLE_SUCCESSFUL =
  "FETCH_ALL_BOOKS_FROM_GOOGLE_SUCCESSFUL";
const FETCH_ALL_BOOKS_FROM_GOOGLE_REJECTED =
  "FETCH_ALL_BOOKS_FROM_GOOGLE_REJECTED";
const FETCH_SINGLE_BOOK_FROM_GOOGLE_PENDING =
  "FETCH_SINGLE_BOOK_FROM_GOOGLE_PENDING";
const FETCH_SINGLE_BOOK_FROM_GOOGLE_SUCCESSFUL =
  "FETCH_SINGLE_BOOK_FROM_GOOGLE_SUCCESSFUL";
const FETCH_SINGLE_BOOK_FROM_GOOGLE_REJECTED =
  "FETCH_SINGLE_BOOK_FROM_GOOGLE_REJECTED";
const CREATE_BOOK_PAYLOAD = "CREATE_BOOK_PAYLOAD";

// FETCH BOOKS FROM MONGO DB
const FETCH_ALL_BOOKS_FROM_MONGODB_PENDING =
  "FETCH_ALL_BOOKS_FROM_MONGODB_PENDING";
const FETCH_ALL_BOOKS_FROM_MONGODB_SUCCESSFUL =
  "FETCH_ALL_BOOKS_FROM_MONGODB_SUCCESSFUL";
const FETCH_ALL_BOOKS_FROM_MONGODB_REJECTED =
  "FETCH_ALL_BOOKS_FROM_MONGODB_REJECTED";
const FETCH_SINGLE_BOOK_FROM_MONGODB_PENDING =
  "FETCH_SINGLE_BOOK_FROM_MONGODB_PENDING";
const FETCH_SINGLE_BOOK_FROM_MONGODB_SUCCESSFUL =
  "FETCH_SINGLE_BOOK_FROM_MONGODB_SUCCESSFUL";
const FETCH_SINGLE_BOOK_FROM_MONGODB_REJECTED =
  "FETCH_SINGLE_BOOK_FROM_MONGODB_REJECTED";

// CHANGE FAVOURITE ICONS
const CHANGE_FAVOURITE_ICON_ON_LOAD = "CHANGE_FAVOURITE_ICON_ON_LOAD";
const ADD_FAVOURITE_ICON = "ADD_FAVOURITE_ICON";
const REMOVE_FAVOURITE_ICON = "REMOVE_FAVOURITE_ICON";

export {
  SAVE_USER,
  REMOVE_USER,
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  FETCH_ALL_BOOKS_FROM_GOOGLE_PENDING,
  FETCH_ALL_BOOKS_FROM_GOOGLE_SUCCESSFUL,
  FETCH_ALL_BOOKS_FROM_GOOGLE_REJECTED,
  FETCH_SINGLE_BOOK_FROM_GOOGLE_PENDING,
  FETCH_SINGLE_BOOK_FROM_GOOGLE_SUCCESSFUL,
  FETCH_SINGLE_BOOK_FROM_GOOGLE_REJECTED,
  CREATE_BOOK_PAYLOAD,
  FETCH_ALL_BOOKS_FROM_MONGODB_PENDING,
  FETCH_ALL_BOOKS_FROM_MONGODB_SUCCESSFUL,
  FETCH_ALL_BOOKS_FROM_MONGODB_REJECTED,
  FETCH_SINGLE_BOOK_FROM_MONGODB_PENDING,
  FETCH_SINGLE_BOOK_FROM_MONGODB_SUCCESSFUL,
  FETCH_SINGLE_BOOK_FROM_MONGODB_REJECTED,
  CHANGE_FAVOURITE_ICON_ON_LOAD,
  ADD_FAVOURITE_ICON,
  REMOVE_FAVOURITE_ICON,
};
